[versions]
java = "21"
springBoot = "3.4.1"
springDependencyManagement = "1.1.7"
springCloud = "2024.0.0"
lombok = "1.18.38"
jib = "3.4.4"
taLib = "0.4.0"
openTelemetry = "1.33.0"
mariadb = "3.5.1"
log4j2 = "2.24.3"
commonsCsv = "1.10.0"
springdoc = "2.8.3"
spotless = "7.0.1"
springAi = "1.1.2"

[libraries]
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mariadb-java-client = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
ta-lib = { group = "com.tictactec", name = "ta-lib", version.ref = "taLib" }
commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commonsCsv" }
springdoc-openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
spring-ai-mcp-server-spring-boot-starter = { group = "org.springframework.ai", name = "spring-ai-starter-mcp-server", version.ref = "springAi" }
mcp-java-sdk = { group = "io.modelcontextprotocol.sdk", name = "mcp", version = "0.17.2" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.25" }
plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "1.9.25" }
plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version = "1.9.25" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
