apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analysis
  labels:
    app: stock-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-analysis
  template:
    metadata:
      labels:
        app: stock-analysis
    spec:
      containers:
        - name: stock-analysis
          image: stock-analysis:latest
          ports:
            - containerPort: 8082
          env:
            - name: STOCK_DB_URL
              value: "http://stock-db-operations:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-analysis
spec:
  selector:
    app: stock-analysis
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
